### ISSUE TITLE
Running bbkbd under other WMs

### ISSUE THREAD

**Issue by sodface** [buildbotics/bbkbd#1]
I've been testing onscreen keyboards in a touchscreen project and I like bbkbd very much. The default behavior with herbstluftwm is nice in that the keyboard does not obscure the contents of the window above but rather the window above resizes to make room for the keyboard below. The only issue I have is that when hiding bbkbd the window above does not resize back to full screen, I have to exit bbkbd completely.  In the screen shots below:

1. bbkbd is running but has not been displayed yet.
2. `pkill -USR1 bbkbd` to display the keyboard (top window resizes)
3. `pkill -USR2 bbkbd` to hide the keyboard (top window does not return to full screen as desired)
4. `killall bbkbd` to exit bbkbd (top window resizes to full screen)

I've tried a couple patches in the keyboard toggle code like lowering the window but it didn't help. Any ideas or do you think this is more a function of the WM?

![2022-09-20-205821_1920x1080_scrot](https://user-images.githubusercontent.com/46695384/191391920-9d71c94a-0bb1-4b48-b225-b139c42a5fa2.png)

![2022-09-20-205630_1920x1080_scrot](https://user-images.githubusercontent.com/46695384/191391940-6500e3dd-73fc-41d2-8f03-a58ea4376c8a.png)

![2022-09-20-205741_1920x1080_scrot](https://user-images.githubusercontent.com/46695384/191391956-68abdfcf-1334-4266-a77a-59bae9978356.png)

![2022-09-20-205821_1920x1080_scrot](https://user-images.githubusercontent.com/46695384/191391966-a68bd4e7-7f6b-4412-ba2d-7845723f4fa6.png)

**Comment by jcoffland** [comment]
bbkbd is itself a very simple WM.  If you run it under another WM it wont function the same.  It's designed for one purpose.  That is to run a keyboard on a touchscreen in combination with a browser.  So it's best if you just run it directly under X with no other WM in between.

**Comment by sodface** [comment]
Understand, thanks for the response.
